title = "CI/CD for Serverless Applications"
baseURL = "https://cicd.serverlessworkshops.io"
languageCode = "en-us"

theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[params]
  author = "Brian Zambrano <zambb@amazon.com>"
  favicon = "https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico"