
name: Add Preview URL
on:
  pull_request:
    branches: [ master ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue: ${{github.event.number}}
          comment: ${{github.head_ref}}
