
name: Add Preview URL
on:
  pull_request:
    branches: [ master ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: |
            Preview your changes here: [https://${{github.head_ref}}.d13cl562h1p8qu.amplifyapp.com](https://${{github.head_ref}}.d13cl562h1p8qu.amplifyapp.com)
